## Himanshu Baweja

## E20CSE212

## Week 7 Lab 2 

In [ ]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.model_selection import train_test_split

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [ ]:
df = pd.read_csv("/content/drive/MyDrive/winequality-red.csv", sep=";")
df

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0               7.4             0.700         0.00             1.9      0.076   
1               7.8             0.880         0.00             2.6      0.098   
2               7.8             0.760         0.04             2.3      0.092   
3              11.2             0.280         0.56             1.9      0.075   
4               7.4             0.700         0.00             1.9      0.076   
...             ...               ...          ...             ...        ...   
1594            6.2             0.600         0.08             2.0      0.090   
1595            5.9             0.550         0.10             2.2      0.062   
1596            6.3             0.510         0.13             2.3      0.076   
1597            5.9             0.645         0.12             2.0      0.075   
1598            6.0             0.310         0.47             3.6      0.067   

      free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                    11.0                  34.0  0.99780  3.51       0.56   
1                    25.0                  67.0  0.99680  3.20       0.68   
2                    15.0                  54.0  0.99700  3.26       0.65   
3                    17.0                  60.0  0.99800  3.16       0.58   
4                    11.0                  34.0  0.99780  3.51       0.56   
...                   ...                   ...      ...   ...        ...   
1594                 32.0                  44.0  0.99490  3.45       0.58   
1595                 39.0                  51.0  0.99512  3.52       0.76   
1596                 29.0                  40.0  0.99574  3.42       0.75   
1597                 32.0                  44.0  0.99547  3.57       0.71   
1598                 18.0                  42.0  0.99549  3.39       0.66   

      alcohol  quality  
0         9.4        5  
1         9.8        5  
2         9.8        5  
3         9.8        6  
4         9.4        5  
...       ...      ...  
1594     10.5        5  
1595     11.2        6  
1596     11.0        6  
1597     10.2        5  
1598     11.0        6  

[1599 rows x 12 columns]

In [ ]:
df.describe()

fixed acidity  volatile acidity  citric acid  residual sugar  \
count    1599.000000       1599.000000  1599.000000     1599.000000   
mean        8.319637          0.527821     0.270976        2.538806   
std         1.741096          0.179060     0.194801        1.409928   
min         4.600000          0.120000     0.000000        0.900000   
25%         7.100000          0.390000     0.090000        1.900000   
50%         7.900000          0.520000     0.260000        2.200000   
75%         9.200000          0.640000     0.420000        2.600000   
max        15.900000          1.580000     1.000000       15.500000   

         chlorides  free sulfur dioxide  total sulfur dioxide      density  \
count  1599.000000          1599.000000           1599.000000  1599.000000   
mean      0.087467            15.874922             46.467792     0.996747   
std       0.047065            10.460157             32.895324     0.001887   
min       0.012000             1.000000              6.000000     0.990070   
25%       0.070000             7.000000             22.000000     0.995600   
50%       0.079000            14.000000             38.000000     0.996750   
75%       0.090000            21.000000             62.000000     0.997835   
max       0.611000            72.000000            289.000000     1.003690   

                pH    sulphates      alcohol      quality  
count  1599.000000  1599.000000  1599.000000  1599.000000  
mean      3.311113     0.658149    10.422983     5.636023  
std       0.154386     0.169507     1.065668     0.807569  
min       2.740000     0.330000     8.400000     3.000000  
25%       3.210000     0.550000     9.500000     5.000000  
50%       3.310000     0.620000    10.200000     6.000000  
75%       3.400000     0.730000    11.100000     6.000000  
max       4.010000     2.000000    14.900000     8.000000

In [ ]:
df.info

<bound method DataFrame.info of       fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0               7.4             0.700         0.00             1.9      0.076   
1               7.8             0.880         0.00             2.6      0.098   
2               7.8             0.760         0.04             2.3      0.092   
3              11.2             0.280         0.56             1.9      0.075   
4               7.4             0.700         0.00             1.9      0.076   
...             ...               ...          ...             ...        ...   
1594            6.2             0.600         0.08             2.0      0.090   
1595            5.9             0.550         0.10             2.2      0.062   
1596            6.3             0.510         0.13             2.3      0.076   
1597            5.9             0.645         0.12             2.0      0.075   
1598            6.0             0.310         0.47             3.6      0.067

In [ ]:
df.shape

(1599, 12)

In [ ]:
df['quality'][0]

5

In [ ]:
for i in range(len(df['quality'])):
  if(df['quality'][i]<=5):
    df['quality'][i]=str(df['quality'][i])
    df['quality'][i] = 'bad'
  elif(df['quality'][i]==6 or df['quality'][i]==7):
    df['quality'][i]=str(df['quality'][i])
    df['quality'][i] = 'Average'
  elif(df['quality'][i]>=8):
    df['quality'][i]=str(df['quality'][i])
    df['quality'][i] = 'Great'

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  This is separate from the ipykernel package so we can avoid doing imports until
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:4: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  after removing the cwd from sys.path.
/usr/local/lib/python3.7/dist-packages/pandas/core/indexing.py:1732: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-ve

In [ ]:
df

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0               7.4             0.700         0.00             1.9      0.076   
1               7.8             0.880         0.00             2.6      0.098   
2               7.8             0.760         0.04             2.3      0.092   
3              11.2             0.280         0.56             1.9      0.075   
4               7.4             0.700         0.00             1.9      0.076   
...             ...               ...          ...             ...        ...   
1594            6.2             0.600         0.08             2.0      0.090   
1595            5.9             0.550         0.10             2.2      0.062   
1596            6.3             0.510         0.13             2.3      0.076   
1597            5.9             0.645         0.12             2.0      0.075   
1598            6.0             0.310         0.47             3.6      0.067   

      free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                    11.0                  34.0  0.99780  3.51       0.56   
1                    25.0                  67.0  0.99680  3.20       0.68   
2                    15.0                  54.0  0.99700  3.26       0.65   
3                    17.0                  60.0  0.99800  3.16       0.58   
4                    11.0                  34.0  0.99780  3.51       0.56   
...                   ...                   ...      ...   ...        ...   
1594                 32.0                  44.0  0.99490  3.45       0.58   
1595                 39.0                  51.0  0.99512  3.52       0.76   
1596                 29.0                  40.0  0.99574  3.42       0.75   
1597                 32.0                  44.0  0.99547  3.57       0.71   
1598                 18.0                  42.0  0.99549  3.39       0.66   

      alcohol  quality  
0         9.4      bad  
1         9.8      bad  
2         9.8      bad  
3         9.8  Average  
4         9.4      bad  
...       ...      ...  
1594     10.5      bad  
1595     11.2  Average  
1596     11.0  Average  
1597     10.2      bad  
1598     11.0  Average  

[1599 rows x 12 columns]

In [ ]:
nu=df.isnull()
nu

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0             False             False        False           False      False   
1             False             False        False           False      False   
2             False             False        False           False      False   
3             False             False        False           False      False   
4             False             False        False           False      False   
...             ...               ...          ...             ...        ...   
1594          False             False        False           False      False   
1595          False             False        False           False      False   
1596          False             False        False           False      False   
1597          False             False        False           False      False   
1598          False             False        False           False      False   

      free sulfur dioxide  total sulfur dioxide  density     pH  sulphates  \
0                   False                 False    False  False      False   
1                   False                 False    False  False      False   
2                   False                 False    False  False      False   
3                   False                 False    False  False      False   
4                   False                 False    False  False      False   
...                   ...                   ...      ...    ...        ...   
1594                False                 False    False  False      False   
1595                False                 False    False  False      False   
1596                False                 False    False  False      False   
1597                False                 False    False  False      False   
1598                False                 False    False  False      False   

      alcohol  quality  
0       False    False  
1       False    False  
2       False    False  
3       False    False  
4       False    False  
...       ...      ...  
1594    False    False  
1595    False    False  
1596    False    False  
1597    False    False  
1598    False    False  

[1599 rows x 12 columns]

In [ ]:
nu[nu.eq('True').any(1)].shape

(0, 12)

In [ ]:
from sklearn.preprocessing import LabelEncoder
df['quality']= LabelEncoder().fit_transform(df['quality'])
df

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0               7.4             0.700         0.00             1.9      0.076   
1               7.8             0.880         0.00             2.6      0.098   
2               7.8             0.760         0.04             2.3      0.092   
3              11.2             0.280         0.56             1.9      0.075   
4               7.4             0.700         0.00             1.9      0.076   
...             ...               ...          ...             ...        ...   
1594            6.2             0.600         0.08             2.0      0.090   
1595            5.9             0.550         0.10             2.2      0.062   
1596            6.3             0.510         0.13             2.3      0.076   
1597            5.9             0.645         0.12             2.0      0.075   
1598            6.0             0.310         0.47             3.6      0.067   

      free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                    11.0                  34.0  0.99780  3.51       0.56   
1                    25.0                  67.0  0.99680  3.20       0.68   
2                    15.0                  54.0  0.99700  3.26       0.65   
3                    17.0                  60.0  0.99800  3.16       0.58   
4                    11.0                  34.0  0.99780  3.51       0.56   
...                   ...                   ...      ...   ...        ...   
1594                 32.0                  44.0  0.99490  3.45       0.58   
1595                 39.0                  51.0  0.99512  3.52       0.76   
1596                 29.0                  40.0  0.99574  3.42       0.75   
1597                 32.0                  44.0  0.99547  3.57       0.71   
1598                 18.0                  42.0  0.99549  3.39       0.66   

      alcohol  quality  
0         9.4        2  
1         9.8        2  
2         9.8        2  
3         9.8        0  
4         9.4        2  
...       ...      ...  
1594     10.5        2  
1595     11.2        0  
1596     11.0        0  
1597     10.2        2  
1598     11.0        0  

[1599 rows x 12 columns]

In [ ]:
from sklearn.preprocessing import MinMaxScaler
mms=MinMaxScaler()
mms.fit_transform(df)

array([[0.24778761, 0.39726027, 0.        , ..., 0.13772455, 0.15384615,
        1.        ],
       [0.28318584, 0.52054795, 0.        , ..., 0.20958084, 0.21538462,
        1.        ],
       [0.28318584, 0.43835616, 0.04      , ..., 0.19161677, 0.21538462,
        1.        ],
       ...,
       [0.15044248, 0.26712329, 0.13      , ..., 0.25149701, 0.4       ,
        0.        ],
       [0.11504425, 0.35958904, 0.12      , ..., 0.22754491, 0.27692308,
        1.        ],
       [0.12389381, 0.13013699, 0.47      , ..., 0.19760479, 0.4       ,
        0.        ]])

In [ ]:
df=pd.DataFrame(df)

In [ ]:
X=df.iloc[:,:-1]
Y=df.iloc[:,-1:]
from sklearn.model_selection import train_test_split as tts
x_train,x_test,y_train,y_test=tts(X,Y,test_size=0.2)

In [ ]:
from sklearn.linear_model import LogisticRegression
clf=LogisticRegression()
clf.fit(x_train,y_train)
ypred=clf.predict(x_test)

/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:818: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG,


In [ ]:
from sklearn.metrics import precision_score,f1_score,recall_score,roc_auc_score,accuracy_score
p=precision_score(y_test,ypred,average=None)
f=f1_score(y_test,ypred,average=None)
r=recall_score(y_test,ypred,average=None)
roc=roc_auc_score(Y,clf.predict_proba(X),multi_class="ovr")

/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [ ]:
print("Precision:",p)
print("F1 SCORE:",f)
print("RECALL SCORE:",r)
print("ROC:",roc)

Precision: [0.78977273 0.         0.70138889]
F1 SCORE: [0.77653631 0.         0.73188406]
RECALL SCORE: [0.76373626 0.         0.76515152]
ROC: 0.7797338011798168


In [ ]:
a1=accuracy_score(y_test,ypred)
a1

0.75

In [ ]:
x_train,x_test,y_train,y_test=tts(X,Y,test_size=0.2)

In [ ]:
from sklearn.decomposition import PCA
pca=PCA(n_components=2)
pca.fit_transform(x_train,y_train)

array([[  4.92857341,  17.22872066],
       [-34.26428746,  -2.82158409],
       [ 14.22381588,  -1.07003466],
       ...,
       [-11.57108104,  -6.72767746],
       [ -0.12472807,  -1.14703096],
       [-32.32573491,  -3.18296237]])

In [ ]:
ypred=clf.predict(x_test)
p=precision_score(y_test,ypred,average=None)
f=f1_score(y_test,ypred,average=None)
r=recall_score(y_test,ypred,average=None)
roc=roc_auc_score(Y,clf.predict_proba(X),multi_class="ovr")

/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [ ]:
a2=accuracy_score(y_test,ypred)
a2

0.684375

In [ ]:
x_train,x_test,y_train,y_test=tts(X,Y,test_size=0.2)

In [ ]:
pca=PCA(n_components=10)
pca.fit_transform(x_train,y_train)

array([[-9.67715573e+00, -7.92184879e+00, -1.63790272e+00, ...,
         7.72305968e-02,  6.81650036e-03,  2.90368187e-02],
       [-3.81763967e+01, -2.57022133e+00, -1.82385004e+00, ...,
        -3.53427126e-02, -3.26522917e-02, -2.87412157e-02],
       [-9.98770668e+00, -4.84154109e+00, -1.53006453e-01, ...,
         1.58171409e-01, -2.76929565e-02,  1.81629896e-02],
       ...,
       [ 1.03849115e+02,  1.35823302e+01,  1.57686731e+00, ...,
         4.91601476e-02, -1.25778634e-01,  5.50189727e-02],
       [ 1.89691505e+01, -8.26443422e+00, -1.44852898e+00, ...,
         8.74231401e-02,  6.20885366e-02, -2.49486082e-02],
       [ 2.63118282e+01,  1.98081735e+01, -5.56127882e-01, ...,
        -1.45592328e-02, -3.47354589e-02,  1.23821101e-02]])

In [ ]:
ypred=clf.predict(x_test)
p=precision_score(y_test,ypred,average=None)
f=f1_score(y_test,ypred,average=None)
r=recall_score(y_test,ypred,average=None)
roc=roc_auc_score(Y,clf.predict_proba(X),multi_class="ovr")

/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [ ]:
a3=accuracy_score(y_test,ypred)
a3

0.7375

In [ ]:
np.cumsum(pca.explained_variance_ratio_)

array([0.94503034, 0.99496328, 0.99751369, 0.99902916, 0.99992778,
       0.99996231, 0.99998044, 0.99999037, 0.99999879, 1.        ])

In [ ]:
x_train,x_test,y_train,y_test=tts(X,Y,test_size=0.2)

In [ ]:
ypred=clf.predict(x_test)
f=f1_score(y_test,ypred,average=None)
clf.score(x_test,y_test)

0.728125